In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
from planet import Session, data_filter, DataClient
from datetime import datetime
import json
import shapely
from shapely.geometry import shape
import pyproj
import ee
# ee.Authenticate()
# ee.Initialize()
import ipyleaflet
import geemap
import shapely.geometry as sg
import numpy as np
import geojson

# INPUT

In [2]:
#area of interest shapefile (should contain only one geometry):

gdf=gpd.read_file('/Users/isabellopez/Desktop/SURGE/notebooks/exploration/data/DISTRICT2011.shp')
aoi_path= gdf[gdf['NAME']=='Jodhpur']

#skysat years (we will only include imagery from March to June. only the most recent images will be used.)
years=[2021, 2022, 2023]

# coverage requirement for final tiles(percent)
crop_coverage_thresh=30

#number of output tiles
tile_n=100

# earth engine crop_class (crops=4)
crop_class=4

overlap_thresh =50

In [3]:
aoi_path

,DIST_ID,NAME,STATE_UT,C_CODE11,TOT_POP,M_POP,F_POP,TOT_L6,M_L6,F_L6,...,P_LIT_POP,P_R_LIT,P_U_LIT,T_P_M_LIT,P_R_M_LIT,P_U_M_LIT,T_P_F_LIT,P_R_F_LIT,P_U_F_LIT,geometry
157,113,Jodhpur,Rajasthan,0811300000000000,3685681,1924326,1761355,592959,313704,279255,...,67.09,59.79,80.23,80.46,76.32,87.81,52.57,41.99,71.85,"POLYGON ((72.26823 27.55385, 72.27026 27.55324..."

---
# CODE
no need to change any code below

## 0. Define utilities

In [4]:
# Utility functions: projecting a feature to the appropriate UTM zone

def get_utm_projection_fcn(geom):
    # define projection
    # from shapely [docs](http://toblerity.org/shapely/manual.html#shapely.ops.transform)
    proj_fcn = partial(
        pyproj.transform,
        pyproj.Proj(init='EPSG:4326'), #wgs84
        pyproj.Proj(_get_utm_projection(geom)))
    return proj_fcn

def _get_utm_zone(geom):
    '''geom: geojson geometry'''
    coordinates = shape(geom)
    lon = coordinates.centroid.x
    lat = coordinates.centroid.y
    
    if lat > 84 or lat < -80:
        raise Exception('UTM Zones only valid within [-80, 84] latitude')
    
    # this is adapted from
    # https://www.e-education.psu.edu/natureofgeoinfo/book/export/html/1696
    zone = int((lon + 180) / 6 + 1)
    
    hemisphere = 'north' if lat > 0 else 'south'
    
    return (zone, hemisphere)

def _get_utm_projection(geom):
    zone,hemisphere= _get_utm_zone(geom)
    if hemisphere =='north':
        proj_str = f"EPSG:326{zone}"
    else:
        proj_str= f"EPSG:327{zone}"
    return proj_str

## 1. Find SkySat coverage

In [5]:
# gdf_shp=gpd.read_file(gdf).geometry.values[0]
aoi_shp=gdf.geometry.values[0]
# aoi_gj= json.loads(shapely.to_geojson(aoi_shp))
def shapely_to_geojson(geometry):
    return geojson.dumps(geometry)
aoi_gj = json.loads(shapely_to_geojson(aoi_shp))
# aoi_gj= json.loads(shapely.to_geojson(aoi_shp))
aoi_crs=_get_utm_projection(aoi_shp)

# create an API Request from the search specifications

item_type = ['SkySatCollect']

geom_filter = data_filter.geometry_filter(aoi_gj)
cloud_cover_filter = data_filter.range_filter('cloud_cover', None, 0.5)
scenes=gpd.GeoDataFrame(pd.DataFrame({'id':[]}), geometry=[],crs='EPSG:4326')
for year in years:
    date_range_filter = data_filter.date_range_filter("acquired", datetime(month=3, day=1, year=year),
                                                      datetime(month=6, day=30, year=year))
    combined_filter = data_filter.and_filter([geom_filter, date_range_filter, cloud_cover_filter])
    async with Session() as sess:
        cl = DataClient(sess)
        items = cl.search(name='calc_coverage_search',search_filter=combined_filter, item_types=item_type, limit=500)
        item_list = [i async for i in items]
        id_list=[i['id'] for i in item_list]
        geom_list=[shape(i['geometry']) for i in item_list]
    
    scenes=pd.concat([scenes, gpd.GeoDataFrame(pd.DataFrame({'id':id_list}), geometry=geom_list,crs='EPSG:4326')])

In [6]:
aoi_crs

'EPSG:32643'

In [7]:
#we do not want a MultiPolygon
# scenes_shp=scenes.geometry.unary_union
scenes

,id,geometry
0,20210629_083200_ssc11_u0002,"POLYGON ((77.47690 35.46244, 77.47693 35.46244..."
1,20210629_052927_ssc2_u0001,"POLYGON ((73.83893 34.23934, 73.83906 34.23396..."
2,20210628_092525_ssc19_u0002,"POLYGON ((73.86181 33.42703, 73.84943 33.41647..."
3,20210628_092525_ssc19_u0003,"POLYGON ((73.94605 33.35634, 73.93385 33.34567..."
4,20210628_092525_ssc19_u0001,"POLYGON ((73.76180 33.51076, 73.74954 33.50006..."
...,...,...
380,20230305_044349_ssc2_u0001,"POLYGON ((75.56338 35.27330, 75.56319 35.27397..."
381,20230305_031221_ssc14_u0001,"POLYGON ((73.43765 34.34714, 73.43758 34.34041..."
382,20230304_090825_ssc6_u0001,"POLYGON ((73.89663 33.35307, 73.89674 33.35304..."
383,20230303_053546_ssc1_u0001,"POLYGON ((73.84491 34.19028, 73.84373 34.18210..."
384,20230303_050258_ssc12_u0002,"POLYGON ((73.48724 34.41583, 73.48729 34.41612..."

## 2. Filter scenes to contain only more than 30 percent crops

In [8]:
def scene_filter(scene, crop_class):
     # Define the visualization parameters for the crop layer
    cropVis = {"min":0, "max":1, 'palette': ['black', '#E49635']}

    legend_dict = {'Crops': '#E49635'}

    # resolution
    scale=10

    cropVis2 = {"min":0, "max":1, 'palette': ['black', '#34EBE1']}

    legend_dict2 = {'Crops': '#34EBE1'}
    
    aoi_json=json.loads(shapely_to_geojson(scene['geometry'].values[0]))
    roi = ee.Geometry.Polygon(aoi_json['coordinates'])
    
    landcover = ee.ImageCollection("GOOGLE/DYNAMICWORLD/V1").filterDate("2015-01-1","2023-05-19").filterBounds(roi).select('label')

    # Create a binary layer where 1 represents crop and 0 represents all other landcover types
    landcover_crop = landcover.map(lambda image: image.eq(crop_class))

    crops = landcover_crop.mosaic().clip(roi).selfMask()
    vectors = crops.reduceToVectors(eightConnected=False, geometryType='polygon', 
                                    crs=crops.projection(), scale=scale).union(1).getInfo()
    
    crops_gdf=gpd.GeoDataFrame({'geometry':[shape(vectors['features'][0]['geometry'])]})
    percent_coverage=100*crops_gdf.set_crs(4326).to_crs(32643).area.values[0]/scene.to_crs(aoi_crs).area.values[0]
    
    return gpd.GeoDataFrame({'id':[scene.id.values[0]], 'coverage':[percent_coverage], 'geometry':[scene.geometry.values[0]]})

In [164]:
jaipur_centroid = aoi_path.geometry.centroid
jaipur_centroid

145    POINT (75.71648 26.96829)
dtype: geometry

In [ ]:
Map = geemap.Map()
Map

Map(center=[20, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], widget=HBox(children=(Togg…

In [18]:
# a= scene_filter(Map, scenes[:1], crop_class)
# a

In [19]:
# crop_cov=gpd.read_file('data/crop_cov_temp.shp')
crop_cov=gpd.GeoDataFrame({'id':[], 'coverage':[], 'geometry':[]}).set_crs(4326)
for i in range(len(crop_cov), len(scenes)):
    print(f'{i}/{len(scenes)-1}')
    crop_cov=pd.concat([crop_cov,scene_filter(scenes[i:i+1], crop_class)])
    # crop_cov.to_file('crop_cov_temp.shp')

0/1273
1/1273
2/1273
3/1273
4/1273
5/1273
6/1273
7/1273
8/1273
9/1273
10/1273
11/1273
12/1273
13/1273
14/1273
15/1273
16/1273
17/1273
18/1273
19/1273
20/1273
21/1273
22/1273
23/1273
24/1273
25/1273
26/1273
27/1273
28/1273
29/1273
30/1273
31/1273
32/1273
33/1273
34/1273
35/1273
36/1273
37/1273
38/1273
39/1273
40/1273
41/1273

EEException: Invalid geometry.

In [357]:
crop_cov

,id,coverage,geometry
0,20210622_051753_ssc3_u0001,4.094752,"POLYGON ((75.79765 26.84055, 75.79775 26.83384..."
1,20210621_082626_ssc10_u0001,3.863074,"POLYGON ((75.78060 26.86223, 75.78074 26.85491..."
2,20210616_054209_ssc17_u0001,4.137158,"POLYGON ((75.79840 26.84188, 75.79843 26.83578..."
3,20210610_015139_ssc15_u0001,11.325827,"POLYGON ((75.82686 26.75873, 75.82692 26.75873..."
4,20210521_004234_ssc19_u0001,3.791677,"POLYGON ((75.78080 26.86385, 75.78088 26.86385..."
5,20210505_082107_ssc8_u0001,11.069189,"POLYGON ((75.83265 26.75305, 75.83269 26.74751..."
6,20210421_060737_ssc14_u0002,12.618217,"POLYGON ((75.73897 26.93681, 75.73909 26.93696..."
7,20210421_060737_ssc14_u0001,5.698053,"POLYGON ((75.85903 26.86658, 75.85921 26.86682..."
8,20210420_063217_ssc15_u0002,11.297733,"POLYGON ((75.74890 26.93159, 75.75460 26.92825..."
9,20210420_063217_ssc15_u0001,6.026572,"POLYGON ((75.86345 26.86430, 75.86927 26.86085..."
10,20210415_055118_ssc17_u0002,8.373219,"POLYGON ((75.86977 26.96458, 75.86940 26.95840..."
11,20210415_055118_ssc17_u0001,10.100374,"POLYGON ((75.86294 26.84170, 75.86301 26.84170..."
12,20210403_055410_ssc1_u0001,13.696574,"POLYGON ((74.99182 26.94133, 74.99198 26.94132..."
13,20210401_082922_ssc8_u0001,10.915117,"POLYGON ((75.83252 26.75678, 75.83257 26.74949..."
14,20210302_055618_ssc1_u0001,9.293117,"POLYGON ((75.79295 26.76181, 75.79311 26.76181..."
15,20220524_051051_ssc12_u0004,41.659474,"POLYGON ((75.39937 27.17459, 75.39938 27.17460..."
16,20220524_051051_ssc12_u0003,46.407888,"POLYGON ((75.53464 27.10782, 75.53464 27.10783..."
17,20220524_051051_ssc12_u0002,71.612507,"POLYGON ((75.66967 27.03944, 75.66973 27.03954..."
18,20220524_051051_ssc12_u0001,25.361464,"POLYGON ((75.80573 26.97047, 75.80588 26.97076..."
19,20220524_010936_ssc19_u0001,71.396601,"POLYGON ((76.22125 27.02244, 76.20953 27.01178..."
20,20220524_010936_ssc19_u0002,72.159822,"POLYGON ((76.31487 26.93988, 76.30328 26.92894..."
21,20220520_084143_ssc10_u0001,19.836762,"POLYGON ((75.85384 26.71469, 75.85389 26.71469..."
22,20220519_083856_ssc8_u0001,77.696718,"POLYGON ((76.23630 27.80560, 76.24247 27.80129..."
23,20220519_083856_ssc8_u0002,70.705147,"POLYGON ((76.35902 27.71832, 76.36517 27.71400..."
24,20220503_050153_ssc3_u0001,12.607670,"POLYGON ((75.81180 26.74129, 75.81188 26.73437..."
25,20220502_050754_ssc13_u0001,4.166478,"POLYGON ((75.75454 26.82089, 75.75461 26.82089..."
26,20220428_051006_ssc2_u0002,77.598364,"POLYGON ((76.32596 27.68782, 76.33134 27.68260..."
27,20220428_051006_ssc2_u0001,75.276676,"POLYGON ((76.21941 27.79404, 76.22486 27.78877..."
28,20220424_055336_ssc1_u0001,3.841114,"POLYGON ((75.77859 26.86854, 75.77874 26.86855..."
29,20220411_084414_ssc8_u0006,69.751132,"POLYGON ((76.14560 27.73554, 76.14564 27.73554..."
30,20220411_084414_ssc8_u0005,80.509541,"POLYGON ((76.16427 27.84572, 76.16432 27.84572..."
31,20220410_083620_ssc10_u0001,8.730522,"POLYGON ((75.01002 26.91835, 75.01002 26.91143..."
32,20220410_045735_ssc13_u0002,64.983807,"POLYGON ((76.39960 27.50327, 76.39960 27.50333..."
33,20220410_045735_ssc13_u0001,75.121029,"POLYGON ((76.21021 27.53376, 76.21022 27.53380..."
34,20220408_051215_ssc2_u0003,52.028586,"POLYGON ((75.43431 27.29638, 75.43511 27.28870..."
35,20220407_050409_ssc13_u0001,9.719063,"POLYGON ((75.83273 26.76420, 75.83290 26.76419..."
36,20220401_050031_ssc2_u0001,58.588097,"POLYGON ((75.89302 26.64458, 75.89311 26.63729..."
37,20220326_050837_ssc4_u0001,9.252312,"POLYGON ((75.01137 26.92136, 75.01145 26.92136..."
38,20220322_083235_ssc10_u0001,4.105189,"POLYGON ((75.79854 26.83879, 75.79851 26.83037..."
39,20220321_083221_ssc8_u0003,53.460748,"POLYGON ((76.22560 27.33368, 76.23338 27.33304..."
40,20220321_083221_ssc8_u0002,49.154756,"POLYGON ((76.06884 27.34735, 76.07703 27.34675..."
41,20220321_083221_ssc8_u0001,48.860491,"POLYGON ((75.90993 27.36062, 75.90993 27.36063..."
42,20220320_083651_ssc7_u0002,65.550403,"POLYGON ((76.26310 27.67735, 76.26618 27.67057..."
43,20220320_083651_ssc7_u0001,79.351647,"POLYGON ((76.20238 27.81345, 76.20546 27.80666..."
44,20220320_083651_ssc7_u0003,76.830155,"POLYGON ((76.32449 27.54021, 76.32753 27.53344..."
45,20220312_051456_ssc2_u0001,9.561834,"POLYGON ((75.79277 26.76393, 75.79290 26.75696..."
46,20220311_083114_ssc9_u0001,11.246809,"POLYGON ((75.75250 26.88378, 75.75258 26.88378..."
47,20220311_083037_ssc9_u0001,51.030804,"POLYGON ((75.81448 27.32033, 75.81460 27.32033..."
48,20220303_083504_ssc8_u0002,31.681260,"POLYGON ((75.91723 26.79564, 75.91727 26.78854..."
49,20220303_083504_ssc8_u0001,24.948160,"POLYGON ((75.91689 26.86077, 75.91691 26.86077..."
50,20220303_025838_ssc16_u0001,34.509779,"POLYGON ((75.67676 26.87436, 75.67679 26.86826..."
51,20220303_025838_ssc16_u0002,39.058506,"POLYGON ((75.67682 26.78891, 75.67687 26.78283..."
52,20220301_050727_ssc13_u0001,3.554627,"POLYGON ((75.77955 26.86746, 75.77958 26.86746..."
53,20230603_043403_ssc4_u0001,8.848599,"POLYGON ((75.83258 26.76585, 75.83264 26.76585..."
54,20230531_085922_ssc6_u0001,14.956216,"POLYGON ((75.87728 26.83555, 75.87739 26.82833..."
55,20230405_053322_ssc1_u0001,8.800867,"POLYGON ((75.00977 26.91979, 75.00992 26.91978..."
56,20230325_085327_ssc7_u0001,13.125557,"POLYGON ((74.99402 26.94240, 74.99411 26.93555..."
57,20230305_044617_ssc2_u0001,11.532614,"POLYGON ((75.83148 26.75506, 75.83155 26.74796..."
58,20230304_084743_ssc10_u0001,12.218920,"POLYGON ((75.03159 26.94310, 75.03160 26.94310..."
59,20230301_051342_ssc14_u0001,16.067399,"POLYGON ((75.85938 26.85801, 75.85939 26.85801..."

In [300]:
chosen_scenes=crop_cov[crop_cov.coverage>=crop_coverage_thresh]

#save chosen scenes into a shapefile
chosen_scenes.to_file(f'chosen_scenes_{crop_coverage_thresh}_percent.shp')

In [301]:
chosen_scenes

,id,coverage,geometry
0,20220524_051051_ssc12_u0004,41.659474,"POLYGON ((75.39937 27.17459, 75.39938 27.17460..."
0,20220524_051051_ssc12_u0003,46.407888,"POLYGON ((75.53464 27.10782, 75.53464 27.10783..."
0,20220524_051051_ssc12_u0002,71.612507,"POLYGON ((75.66967 27.03944, 75.66973 27.03954..."
0,20220524_010936_ssc19_u0001,71.396601,"POLYGON ((76.22125 27.02244, 76.20953 27.01178..."
0,20220524_010936_ssc19_u0002,72.159822,"POLYGON ((76.31487 26.93988, 76.30328 26.92894..."
0,20220519_083856_ssc8_u0001,77.696718,"POLYGON ((76.23630 27.80560, 76.24247 27.80129..."
0,20220519_083856_ssc8_u0002,70.705147,"POLYGON ((76.35902 27.71832, 76.36517 27.71400..."
0,20220428_051006_ssc2_u0002,77.598364,"POLYGON ((76.32596 27.68782, 76.33134 27.68260..."
0,20220428_051006_ssc2_u0001,75.276676,"POLYGON ((76.21941 27.79404, 76.22486 27.78877..."
0,20220411_084414_ssc8_u0006,69.751132,"POLYGON ((76.14560 27.73554, 76.14564 27.73554..."
0,20220411_084414_ssc8_u0005,80.509541,"POLYGON ((76.16427 27.84572, 76.16432 27.84572..."
0,20220410_045735_ssc13_u0002,64.983807,"POLYGON ((76.39960 27.50327, 76.39960 27.50333..."
0,20220410_045735_ssc13_u0001,75.121029,"POLYGON ((76.21021 27.53376, 76.21022 27.53380..."
0,20220408_051215_ssc2_u0003,52.028586,"POLYGON ((75.43431 27.29638, 75.43511 27.28870..."
0,20220401_050031_ssc2_u0001,58.588097,"POLYGON ((75.89302 26.64458, 75.89311 26.63729..."
0,20220321_083221_ssc8_u0003,53.460748,"POLYGON ((76.22560 27.33368, 76.23338 27.33304..."
0,20220321_083221_ssc8_u0002,49.154756,"POLYGON ((76.06884 27.34735, 76.07703 27.34675..."
0,20220321_083221_ssc8_u0001,48.860491,"POLYGON ((75.90993 27.36062, 75.90993 27.36063..."
0,20220320_083651_ssc7_u0002,65.550403,"POLYGON ((76.26310 27.67735, 76.26618 27.67057..."
0,20220320_083651_ssc7_u0001,79.351647,"POLYGON ((76.20238 27.81345, 76.20546 27.80666..."
0,20220320_083651_ssc7_u0003,76.830155,"POLYGON ((76.32449 27.54021, 76.32753 27.53344..."
0,20220311_083037_ssc9_u0001,51.030804,"POLYGON ((75.81448 27.32033, 75.81460 27.32033..."
0,20220303_083504_ssc8_u0002,31.681260,"POLYGON ((75.91723 26.79564, 75.91727 26.78854..."
0,20220303_025838_ssc16_u0001,34.509779,"POLYGON ((75.67676 26.87436, 75.67679 26.86826..."
0,20220303_025838_ssc16_u0002,39.058506,"POLYGON ((75.67682 26.78891, 75.67687 26.78283..."

# 3. Remove Overlapping Scenes

In [333]:
def remove_overlapping_scenes(scenes):
    non_overlapping_scenes = gpd.GeoDataFrame({'id':[], 'coverage':[], 'geometry':[]}).set_crs(4326)
    while len(scenes) > 0:
        scene1 = scenes.iloc[0]
        scenes.drop(0, inplace= True)
        scenes.reset_index(inplace=True)
        scenes.drop(columns='index',inplace= True)
        # overlapping = [i for i in range(len(scenes)) if scene1['geometry'].intersects(scenes['geometry'].values[i])]
        overlapping = [i for i in range(len(scenes)) if 100*(scene1['geometry'].intersection(scenes['geometry'].values[i]).area)/scene1['geometry'].area>overlap_thresh]
        keep=True
        for i in overlapping:
            if scene1['coverage'] > scenes['coverage'].values[i]:  # scene1 has more coverage, so remove scene2
                scenes.drop(i, inplace= True)
            else:  # scene2 has more coverage, so remove scene1 and break the loop
                keep= False
                break
        if keep:
            non_overlapping_scenes=pd.concat([non_overlapping_scenes,
                                              gpd.GeoDataFrame({'id':[scene1['id']], 
                                                                'coverage':[scene1['coverage']],
                                                                'geometry':[scene1['geometry']]}).set_crs(4326)])
        scenes.reset_index(inplace=True)
        scenes.drop(columns='index',inplace= True)
    return non_overlapping_scenes

In [335]:
chosen_scenes = gpd.read_file(f'data/chosen_scenes_{crop_coverage_thresh}_percent.shp')
chosen_scenes

,id,coverage,geometry
0,20220524_051051_ssc12_u0004,41.659474,"POLYGON ((75.39937 27.17459, 75.39938 27.17460..."
1,20220524_051051_ssc12_u0003,46.407888,"POLYGON ((75.53464 27.10782, 75.53464 27.10783..."
2,20220524_051051_ssc12_u0002,71.612507,"POLYGON ((75.66967 27.03944, 75.66973 27.03954..."
3,20220524_010936_ssc19_u0001,71.396601,"POLYGON ((76.22125 27.02244, 76.20953 27.01178..."
4,20220524_010936_ssc19_u0002,72.159822,"POLYGON ((76.31487 26.93988, 76.30328 26.92894..."
5,20220519_083856_ssc8_u0001,77.696718,"POLYGON ((76.23630 27.80560, 76.24247 27.80129..."
6,20220519_083856_ssc8_u0002,70.705147,"POLYGON ((76.35902 27.71832, 76.36517 27.71400..."
7,20220428_051006_ssc2_u0002,77.598364,"POLYGON ((76.32596 27.68782, 76.33134 27.68260..."
8,20220428_051006_ssc2_u0001,75.276676,"POLYGON ((76.21941 27.79404, 76.22486 27.78877..."
9,20220411_084414_ssc8_u0006,69.751132,"POLYGON ((76.14560 27.73554, 76.14564 27.73554..."
10,20220411_084414_ssc8_u0005,80.509541,"POLYGON ((76.16427 27.84572, 76.16432 27.84572..."
11,20220410_045735_ssc13_u0002,64.983807,"POLYGON ((76.39960 27.50327, 76.39960 27.50333..."
12,20220410_045735_ssc13_u0001,75.121029,"POLYGON ((76.21021 27.53376, 76.21022 27.53380..."
13,20220408_051215_ssc2_u0003,52.028586,"POLYGON ((75.43431 27.29638, 75.43511 27.28870..."
14,20220401_050031_ssc2_u0001,58.588097,"POLYGON ((75.89302 26.64458, 75.89311 26.63729..."
15,20220321_083221_ssc8_u0003,53.460748,"POLYGON ((76.22560 27.33368, 76.23338 27.33304..."
16,20220321_083221_ssc8_u0002,49.154756,"POLYGON ((76.06884 27.34735, 76.07703 27.34675..."
17,20220321_083221_ssc8_u0001,48.860491,"POLYGON ((75.90993 27.36062, 75.90993 27.36063..."
18,20220320_083651_ssc7_u0002,65.550403,"POLYGON ((76.26310 27.67735, 76.26618 27.67057..."
19,20220320_083651_ssc7_u0001,79.351647,"POLYGON ((76.20238 27.81345, 76.20546 27.80666..."
20,20220320_083651_ssc7_u0003,76.830155,"POLYGON ((76.32449 27.54021, 76.32753 27.53344..."
21,20220311_083037_ssc9_u0001,51.030804,"POLYGON ((75.81448 27.32033, 75.81460 27.32033..."
22,20220303_083504_ssc8_u0002,31.681260,"POLYGON ((75.91723 26.79564, 75.91727 26.78854..."
23,20220303_025838_ssc16_u0001,34.509779,"POLYGON ((75.67676 26.87436, 75.67679 26.86826..."
24,20220303_025838_ssc16_u0002,39.058506,"POLYGON ((75.67682 26.78891, 75.67687 26.78283..."

In [337]:
chosen_scenes = remove_overlapping_scenes(chosen_scenes)

#save chosen scenes that are not overlapping into a shapefile
# chosen_scenes.to_file(f'no_overlapping_{crop_coverage_thresh}_percent.shp')

In [338]:
chosen_scenes.explore()

In [331]:
scene1=scenes.geometry.values[0]
scene2=scenes.geometry.values[1]
100*(scene1.intersection(scene2)).area/scene1.area

84.58992557971649

In [329]:
scene1.area

0.0075501605825293435

In [330]:
scene2.area

0.00741651992704897